### PR TITLE
Test parameter values in truffleAssert.eventEmitted

### PR DESCRIPTION
**Pull request by CodinMaster**

### CODE REVIEW

**Comment by tauren** [comment]
@CodinMaster thanks for solving `eventEmitted` parameter testing!

**Comment by tauren** [comment]
@CodinMaster can you point me to any resources that show that using strings in the way you are is more desirable? I'd like to read up on that before landing this PR.

**Comment by CodinMaster** [comment]
You can read here: https://ethereum.stackexchange.com/a/67094/54653
Though in this case, as the values are low (100 and 30) we can directly use Number, and convert it to string inside `assertCreateMoneyPoolEvent`, etc. for comparing with event params.

**Comment by tauren** [comment]
Thanks, I'll review that. 

Would you mind updating your PR based on the latest `main`, as it now has merge conflicts? Thanks!

**Comment by CodinMaster** [comment]
Updated. The event assertions now work with both Number and String.

**Comment by tauren** [comment]
Landed. Looks great, thanks for the contribution!

**Pull request merged**
